KimiNewt/pyshark

src/pyshark/capture/capture.py, src/pyshark/tshark/tshark.py, src/setup.py, tests/test_packet_operations.py, tests/test_tshark.py
This PR:
* Moves the display filter determination into its own function
* Adds tests for the `tshark` sub-module's functions
* Adds requirements for `mock` and `pytest` to `setup.py`
__Edited to add__:
* Fixes a test failure
* Fixes #53 (thanks @goretkin and @baszoetekouw)
=> TShark module improvements

src/pyshark/tshark/tshark.py
Hi,
Please accept this fix that makes pyshark search for tshark on the user defined unix PATH.  It should also negate the need for a config.ini, at least on unixy systems.
=> Search entire PATH for tshark instead of depending on hardcoded defaults

README.md, src/pyshark/capture/capture.py, src/pyshark/capture/live_capture.py, tests/test_cap_operations.py
Add output_file parameter to base Capture class and expose it for LiveCapture objects so a file can be created and saved to be inspected using FileCapture later.  This is useful for applying disparate display_filters against a FileCapture object at a later time.
Fix a bug where pyshark would hang attempting to iterate a FileCapture w/ only_summaries=True that had no data due to an applied display_filter.  The root cause was only checking for a 'structure' psml element that would never appear before EOF.  Adding a StreamReader EOF check (empty read) to break out of the loop resolves the problem.  Also added a unit test to add coverage for this scenario and confirmed it would fail when removing the patched code.
=> Add optional 'output_file' parameter to LiveCapture objects and fix hang attempting to iterate an empty FileCapture w/ only_summaries=True

README.md, src/pyshark/capture/capture.py, src/pyshark/capture/file_capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/capture/remote_capture.py, src/pyshark/tshark/tshark.py, tests/test_tshark.py
I'm trying the use of pyshark for doing some basic tests on a Wireshark dissector plugin. In this use case, one would need to setup a `config.ini` file and modify `config.CONFIG_PATH` in order to be able to load `tshark` from the build directory. It would be great to have an optional parameter instead that one can pass to the `Capture` interface.
This is a first try to do this, by using an optional parameter that is put first on the search list. Another valid approach might be to turn the configuration a modifiable structure (a dict?) so one can put the path there.
=> Added optional path parameter to Capture interface

README.md, src/pyshark/__init__.py, src/pyshark/capture/live_ring_capture.py
use ring buffer for live capture so that temp file created by tshark doesn't cause disk space problems in /tmp for longterm continuous captures.
=> issue 92 add ring buffer to live capture

src/pyshark/tshark/tshark.py
Version strings for TSHARK are displayed differently for different installations.
The following were found as a difference between Windows and Linux:
win_version_line = 'TShark 1.12.8 (v1.12.8-0-g5b6e543 from master-1.12)'
lnx_version_line = 'TShark (Wireshark) 2.0.0 (SVN Rev Unknown from unknown)'
lnx_tshark_line = 'TShark 1.2.3'
The current implementation returned "(Wireshark)" in the Linux case, and caused an error in version comparision performed in 'get_tshark_display_filter_flag()'.
=> Updating get_tshark_version() to support multiple version strings

src/pyshark/capture/capture.py, src/pyshark/capture/file_capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/capture/live_ring_capture.py, src/pyshark/capture/remote_capture.py, tests/capture/test_capture.py
Method to resolve issue:
"no interface to add override parameters (can't easily apply wsp.enable_null_encryption_decode_heuristic: TRUE)" #118
This adds a new 'override_prefs' item to the init of Capture and related objects subclassing the Capture object.
Using 'preferences' in place of 'parameters' to match tshark terminology.
:param override_prefs: A dictionary of tshark preferences to override, {PREFERENCE_NAME, PREFERENCE_VALUE, ...}.
There is overlap in what this option provides and the existing decryption_key & encryption_type already provide. The current implementation supports the ability to apply the related encryption preference setting using EITHER decryption_key & encryption_type OR override_perfs.
=> Adding 'override_prefs' to Capture in order to support the ability to override arbitrary tshark preferences

src/pyshark/capture/live_capture.py, src/pyshark/capture/live_ring_capture.py
BFP filter should apply to all interfaces (as there is not option to set it per interface).
This is done by setting the -f (bpf filter) parameter before the first -i (interface).
=> Make sure BPF filter applies to all interfaces

README.md, src/pyshark/capture/capture.py, src/pyshark/capture/file_capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/capture/live_ring_capture.py, src/pyshark/capture/remote_capture.py
In a pet project of mine using this library I needed to disable a specific protocol due to a dissector clash leading to wrong output.
As there is a relatively new parameter for tshark I patched the parameter into the library to use it.
=> Added disable_protocol parameter

src/pyshark/capture/live_capture.py
Because WinPcap does not support monitor mode, running pyshark in monitor mode gives a system crash message. Its nicer to thow an exception in the application itself. https://wiki.wireshark.org/CaptureSetup/WLAN#Monitor_mode
=> Check for the windows platform before starting monitor mode

src/pyshark/capture/capture.py, src/pyshark/capture/file_capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/packet/common.py, src/pyshark/packet/fields.py, src/pyshark/packet/layer.py, src/pyshark/tshark/tshark.py, src/pyshark/tshark/tshark_json.py, src/pyshark/tshark/tshark_xml.py, src/setup.py
This branch adds an experimental capacity to use JSON instead of XML parsing with tshark. This is a feature from Wireshark 2.2.0. It is not the default option.
Please review and make suggestions.
The speed-up is considerable, however multiple things should be noted:
- The JSON does not contain the same amount of information the XML does. The actual value of the field is present but the "nice" value and presentation are not. As such, I recommend it for programmatic use but not for interactive use (where performance is not important anyway).
- Field names may be slightly different, and in particular I use a different nesting for tree fields, which is to say that instead of accessing an inner field in a flat way like `pkt.tcp.flags_ack` you will access it via `pkt.tcp.flags.ack`. 
- Because …
=> Using tshark JSON output to speed up pyshark

src/pyshark/packet/fields.py
Like **'Opcode: ACCESS (3), [Check: RD LU MD XT DL]'**,
`LayerField.showname_value()` will give **'ACCESS (3), [Check'** without `maxsplit=1`.
=> Update showname_value() to support string with more than one colon.

src/pyshark/tshark/tshark.py
Not suppressing stderr leads to leaking of the warning/error messages
all the way up to the parent process.
=> tshark: Suppress stderr when checking tshark version and interfaces

src/pyshark/capture/live_capture.py, tests/capture/test_live_capture.py
Proposed fix for #213 
according to the _get_dumpcap_parameters method of Capture, interfaces are ignored if monitor mode is enabled.
I checked with dumpcap / tshark in version 2.2.6 and it seemed to work quite well.
Just changed the if statement and wrote a simple test for that
=> add interfaces to dumpcap parameters even in monitor mode

src/pyshark/tshark/tshark.py
Fix bug when run `pyshark.tshark.tshark.get_tshark_interfaces()` on python3.
It seems that the problem is caused by some non printable character.
The `check_output` function returned string like this on my windows matchine.
```
b'1. \\Device\\NPF_{D4C6D5DC-6623-4D63-B8A4-6A9C0FA8DC21} (\xe6\x97\xa0\xe7\xba\xbf\xe7\xbd\x91\xe7\xbb\x9c\xe8\xbf\x9e\xe6\x8e\xa5 3)\r\n2. \\Device\\NPF_{DD4CCD84-B30B-445F-9B7D-5FEDF637B29D} (\xe6\x97\xa0\xe7\xba\xbf\xe7\xbd\x91\xe7\xbb\x9c\xe8\xbf\x9e\xe6\x8e\xa5)\r\n3. \\Device\\NPF_{DA8D6FF0-C4B8-47F8-A5F3-D5DACE77ECDF} (\xe6\x9c\xac\xe5\x9c\xb0\xe8\xbf\x9e\xe6\x8e\xa5)\r\n4. \\Device\\NPF_{FD96E1C4-8681-4E6E-B543-8C847633095D} (Bluetooth \xe7\xbd\x91\xe7\xbb\x9c\xe8\xbf\x9e\xe6\x8e\xa5 2)\r\n5. \\Device\\NPF_{E98BA79E-63A9-4EE1-8AFE-0CBBE93E42AD} (VMware …
```
=> Fix UnicodeDecodeError

src/pyshark/packet/common.py, src/pyshark/packet/fields.py
Fixed issue of being unable to unpickle captured packets due to error occuring in overriden __new__ method in LayerFieldsContainer.
Took edits from @alagoa pull request #271 and made edits in common.py for python3 compatibility.
Resolves #63 #169
=> Pickle/Unpickle of Captured Packets

src/pyshark/capture/capture.py
The debug line fixed is currently displayed as:
DEBUG: LiveCapture: %s subprocess created
With this fix, it will be properly displayed as:
DEBUG: LiveCapture: TShark subprocess created
=> Fix debug output

src/pyshark/packet/packet.py
From my testing, get_raw_packet would try to run binascii.unhexlify() against the first self.frame_raw.value, which fails because binascii.unhexlify() needs a hex value.
This pull request fixes that and means that calling Packet.get_raw_packet() returns what I expect is the intended result, a raw binary version of the packet.
=> Fixing get_raw_packet

src/pyshark/packet/fields.py
I have faced a situation when sniffer crashes in case of below TCP Flag value:
`{'size': '2', 'unmaskedvalue': 'a002', 'name': 'tcp.flags', 'value': '2', 'show': '0x00000002', 'pos': '46', 'showname': 'Flags: 0x002 (SYN)'}`
There is a `binascii.unhexlify` call in below function. It requires **hex** string to be of even length.
However, a packet flag has produced odd length string (`'value': '2'` as in above example).
So I have added handling for this case. I have tested it and it seems to work fine.
Could you please accept this fix in main repo?
Thanks,
Paul
=> Handle case when 'hex' string is of odd length (to pad with zeros)

src/pyshark/capture/live_capture.py, tests/capture/test_live_capture.py
Now you can pass filters like "tcp port 80" without any troubles.
Command execution function changed from asyncio.create_subprocess_exec to asyncio.create_subprocess_shell
=> Fixed bug with bpf filter string contained spaces.

src/pyshark/capture/capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/tshark/tshark.py, tests/test_tshark.py
Solves #248 
Wireshark fix: https://code.wireshark.org/review/#/c/24536/
=> Using pcapng in dumpcap when tshark>2.5, caching tshark version

src/pyshark/capture/capture.py
Hi, I was tired of being spammed by those resource warnings :
```
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
stdin=stdin)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
So I changed the `open()` call to `DEVNULL` from subprocess. The file descriptor is automatically closed. However this is Python >= 3.3, hope it's ok !
#26 related
=> Fix ResourceWarning by using subprocess' DEVNULL

src/pyshark/capture/capture.py
This fixes an issue with Live Capture's sniff.  It would always pass packet_count as None to the subprocess.  This meant the subprocess did not correctly finish when packet count was reached and would terminate incorrectly, often resulting in a corrupt or blank output_file.
Timeout is still an issue
=> Fix for output_file when packet_count reached

src/pyshark/packet/layer.py
This fixes an issue with using JSON in FileCapture. The `_convert_showname_field_names_to_field_names()` function would throw the `dictionary changed size during iteration` error because a key could be popped from the dictionary during the for loop over the dict keys. The solution is to loop over a copy of the keys by wrapping the returned iterator in `list()`.
Fixes KimiNewt/pyshark#420
=> Fix for the "dictionary changed size during iteration" error when using json with FileCapture

src/pyshark/tshark/tshark_json.py
In the default xml mode, pyshark expects Unix time in the 'packet.sniff_timestamp' and date time in the 'packet.sniff_time" (see the 'Packet' class and the 'sniff_time' function of the class for details).
In the json capture, the two types of time were confused, leading to the following error `ValueError: could not convert string to float: Jan XX, 20XX HH:MM:SS` in the `sniff_time` function.
To save the correct timestamp in a packet, the `time_epoch` value of the frame, which represents the Unix time, should be used.
=> Fixing the sniff timestamp of a packet in the use_json mode

src/pyshark/tshark/tshark.py
Output example:
unix:
1. veth44bb9fb
2. veth00863cf
3. eth0
4. veth4ff8cd1
5. veth2ecda2a
6. br-cb423efa22d6
...
Windows:
1. \Device\NPF_{2D2C765C-35AC-4DB6-7KJd-4211E322ED6D} (Local Area Connection* 8)
2. \Device\NPF_{9105521D-80EC-4C2A-95K9-C100FCA7EC8B} (Local Area Connection* 7)
3. \Device\NPF_{AFD838D6-D3D9-47D8-ABE7-B1824198D3EA} (VirtualBox Host-Only Network)
4. \Device\NPF_{94CACD78-2EDD-4F65-8788-354803DF9BD7} (Ethernet 2)
5. \Device\NPF_{D40E026A-BE8F-4490-WYZ7-8CD232CFEC43} (Local Area Connection* 6)
6. \Device\NPF_{A7A2D260-7445-4EB4-840D-F82819AEE871} (Ethernet)
7. \Device\NPF_Loopback (Adapter for loopback traffic capture)
...
Previous implementation returns [1, 2, 3...] instead of list with interface names
=> Fix wrong get_interfaces implementation

src/pyshark/capture/capture.py
The same problem like #402
```
Exception ignored in: <function Capture.__del__ at 0x10a564430>
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 436, in __del__
self.close()
File "/usr/local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 427, in close
self.eventloop.run_until_complete(self.close_async())
File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/usr/local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 431, in close_async
await self._cleanup_subprocess(process)
File "/usr/local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 413, in …
```
=> Timeout error is `asyncio.exceptions.TimeoutError` in python 3.8

src/pyshark/capture/inmem_capture.py
It would be useful to be able to configure the tshark timeout when calling parse_packet/parse_packets/parse_packets_async.
Users can currently change the timeout by doing the following, but doing so via a function call is preferable.
```python
import pyshark.capture.inmem_capture
pyshark.capture.inmem_capture.DEFAULT_TIMEOUT = 600
```
Users can disable the timeout by passing `None`.
=> Allow configuring the tshark timeout in InMemCapture

src/pyshark/config.py
This PR replaces py.iniconfig with the standard library configparser.
There are two benefits
1) Make pyshark work better with pyinstaller, so a fix for issue #245 which was caused by py
2) py library is in maintenance mode since October 2017 and it not intended to be used for new projects (see https://pypi.org/project/py/). The latest python version officially supported by py is 3.7.
This PR allows pyshark to work in an exe created by pyinstaller which was caused by issues with the py library.
The py library is still used for the TerminalWriter in pretty_print so it's not removed completely by this PR, so if an application uses that functionality they would still have issues with pyinstaller. But this PR will fix it for most use cases.
=> Use configparser in config.py (work better with pyinstaller)

src/pyshark/tshark/tshark_xml.py
There are multiple problems when pyshark receives invalid output from tshark. 
The first problem is when invalid UTF-8 encodings are present in the tshark output. These make pyshark terminate with an XMLSyntaxError exception. The problem was first mentioned five years ago and several duplicate bug reports were filed over the years:
- Issue #116
- Issue #454
- Issue #470 
The second problem is when the tshark output contains invalid XML characters, such as control characters with codes below ASCII 32. These are silently handled by the XML parser running in recovery mode, but not in a satisfying way. When an invalid character is present in an element attribute, the remaining attributes are skipped, which leads to fields being silently lost.
The proposed fix for the UTF-8 encoding problem is …
=> Fix for handling invalid output by tshark.

src/setup.py
Allow third-party tools (e. g., PyPI or `pyp2rpm`) to get the license details in a simple way.
=> Add license tag

.travis.yml, requirements.txt, src/pyshark/capture/__init__.py, src/pyshark/capture/capture.py, src/pyshark/capture/inmem_capture.py, src/pyshark/capture/live_capture.py, src/pyshark/tshark/tshark.py, src/setup.py, src/tox.ini, tests/capture/test_inmem_capture.py, tests/capture/test_live_capture.py, tests/test_cap_operations.py, tests/test_tshark.py
I **replaced the distutils package with the packaging package**, cause distutils is deprecated and will be removed in Python 3.12. The recommended replacement is setuptools which uses packaging. For pyshark only the ability to compare versions is needed. This functionality is provided by packaging. To keep dependencies slim, I choose packaging over setuptools.
asyncio get_event_loop method is also deprecated in Python 3.10 [see](https://docs.python.org/3/library/asyncio-eventloop.html). After fiddling around with nested_asyncio, I realized that nested_asyncio also uses the deprecated get_event_loop method, so I dumped nested_asyncio and **fixed the deprecation warning for the get_event_loop method with "nativ" asyncio methods**.
I also made some small changes to tests in order to prevent …
=> Python 3.10 and Python 3.9 compatibility; disutils deprecation; asyncio method deprecation

src/pyshark/capture/live_capture.py
Tested on ubuntu 20.04, anaconda python 3.7.1, TShark (Wireshark) 3.2.3 (Git v3.2.3 packaged as 3.2.3-1).
https://github.com/KimiNewt/pyshark/issues/477
https://github.com/KimiNewt/pyshark/issues/299
with LiveRingCapture and -r it just crashed, as in these issues. With LiveCapture it would drop packets. With LiveRingCapture and -i it works without dropping packets. I did not run for a long period of time yet to see how long it runs without drops. My packet rate is relatively low.
UPDATE from SquigDawg 2/28/2022:  Found this in poleguy's fork and it fixed the issue I was having.  But [his pull request](https://github.com/poleguy/pyshark/pull/1) wasn't up to the KimiNewt/pyshark parent repo.
=> -r doesn't work, reverting to -i

src/pyshark/tshark/tshark.py
When I provided a `tshark_path` parameter like `D:\\Program Files\\Wireshark\\tshark.exe`, using `LiveCapture` called tshark in Dumpcap subprocess, and nothing captured.
Therefore I tried to run it on a Linux machine which tshark was in the default path, the program captured successfully.
And you can see that the program in Dumpcap subprocess is `dumpcap`.
After carefully reviewing the source code, I find that when user provides his own `tshark_path`, the `process_name` will not be  spliced to `path`, which is the bug of this problem.
The commit https://github.com/KimiNewt/pyshark/commit/85adafac86c13d90d88d31876ff49c6deae57257 did not solve this bug, so in this PR I try to fix it. 
A user can provide a path like `D:\\Program Files\\Wireshark\\tshark.exe` or `D:\\Program …
=> Fix path when user provides `tshark_path` using `LiveCapture`.

src/pyshark/config.py, src/pyshark/tshark/tshark.py
Get `config.ini` from the current directory first, then the pyshark module directory.
Check if the file exists before reading it.
In the `src/pyshark/tshark/tshark.py`, also check if `config.ini` exists before adding it to `possible_paths`.
**The priority that tshark_path loads will be:**
user provided `tshark_path` > `config.ini` in the current directory > `config.ini` in the pyshark module directory > system env
This PR will fix the issue https://github.com/KimiNewt/pyshark/issues/564 .
=> Fix some tshark_path problems.

src/pyshark/capture/live_ring_capture.py
When a user use `LiveRingCapture` with `include_raw=True`, it will return `use_json must be True if include_raw`. However, `LiveRingCapture` doesn't have `use_json` parameter. 
In the source code, I find that `LiveRingCapture` derives from `LiveCapture` but it doesn't provide the proper parameters to be passed to its parent class.
So I add some parameters for `LiveRingCapture` to solve this problem.
=> Add some params for LiveRingCapture.

src/pyshark/capture/live_capture.py
When creating a `RemoteCapture` as
```python 
capture = pyshark.RemoteCapture( '192.168.1.134', remote_interface='en0')
```
The init fails raising an `UnknownInterfaceException` from what I can tell this is simply because `LiveCapture._verify_capture_parameters` do not whitelist rpcap.
=> Accepting rpcap:// as a valid interface name

src/pyshark/capture/remote_capture.py
Add `*args` and `**kwargs` to `RemoteCapture` so that all of `LiveCapture`'s feature can be used (for example `use_json`).
=> Add args and kwargs to RemoteCapture __init__

src/pyshark/packet/packet.py
pyshark v0.5 broke backward compatibility with v0.4.6 by renaming the packet `data` layer to `DATA`. (See issue #637.) This PR makes packet layer names case-insensitive to retain backward and forward compatibility with both names.
=> Make packet layer names case-insensitive for backward compatibility with v0.4.6

src/pyshark/capture/capture.py
See #583 . Reported here:
* System: Windows 10
* Python: 3.10.5
* pyshark: 0.5.3
* Environment: venv
The issues seems to be related to [this](https://docs.python.org/3/whatsnew/3.7.html#asyncio) update.
> The [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio) module has received many new features, usability and [performance improvements](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-asyncio-perf). Notable changes include:
> [...]
> The new [asyncio.current_task()](https://docs.python.org/3/library/asyncio-task.html#asyncio.current_task) function returns the currently running [Task](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task) instance, and the new [asyncio.all_tasks()](https://docs.python.org/3/library/asyncio-task.html#asyncio.all_tasks) …
=> bugfix: deprecated asyncio usage since python 3.9

src/pyshark/capture/capture.py
Breaks `FileCapture`'s `load_packets`. Need to find a better solution (e.g. detecting that the process shut down before checking the EOF in stderr)
Reverts KimiNewt/pyshark#625
=> Revert "stderr closing now triggers end of file processing - added to correct issue623"

src/pyshark/capture/capture.py
In some cases (happens often inside dockers), the stderr handling task doesn't close by itself, so cancelling is required
=> capture: Fix close_async in case the stderr task is still running

src/pyshark/tshark/tshark.py
Right now, a FileCapture will fail if the current working directory has a config.ini file without the config sections it's looking for.
This PR puts the `config.get()` in a try block so it won't fail.
Closes #612
=> Don't fail when the current working directory has a config.ini file

tests/packet/test_fields.py
Fix #701 Tested on Windows 11, Python 3.12.0
This pull request addresses a lack of test coverage for the LayerField and LayerFieldsContainer classes in the source file [src/pyshark/packet/fields.py](https://github.com/KimiNewt/pyshark/blob/master/src/pyshark/packet/fields.py). These tests ensure that functions performing value conversions and string formatting produce the expected results when provided certain values, as well as some functional testing for functions used to modify values within the class.
A new test source file will be added to the tests folder under a new packet directory, which, can also contain tests for the other files under the src/pyshark/packet directory. These tests use the standards pytest library, and follow the same testing conventions as existing tests in the …
=> Adding Test Coverage to Cover the fields.py file for LayerField and LayerFieldsContainer Classes

src/pyshark/packet/fields.py
Added type hints to the non-private methods of the LayerFieldsContainer class to bring in line with LayerField class' type-hinting. Closes issue #714.
=> Added type hints to LayerFieldsContainer class for consistency

src/pyshark/__init__.py, src/pyshark/capture/pipe_capture.py
This PR is a minified version of @CarlyAmars work[1], only enabling PipeCaptures.
[1]: https://github.com/KimiNewt/pyshark/pull/280
=> enable PipeCaptures
