KimiNewt/pyshark

- src/pyshark/config.ini
- src/pyshark/tshark/tshark.py
adding default path in cent os 6...
> added path /usr/sbin

- src/pyshark/capture/capture.py
- src/pyshark/packet/packet.py
- src/pyshark/tshark/tshark_xml.py
Adding packet number info in the Packet object meta info.
Fix WLAN decryption parameters used for tshark.
> Add the packet number in the Packet object while parsing PDML output.

- src/pyshark/capture/capture.py
> Can emit more than one packet per read.

- src/README.txt
- src/pyshark/capture/capture.py
- src/pyshark/capture/live_capture.py
Capture filter is usually better for a live capture than display filter.
> Added capture filter.

- README.md
I thought this tip might help more people get past the (tiny) hurdle of installing libxml.  Sometimes that error message can be a hassle, it's a weird dependency.
> Installation Update

- src/pyshark/capture/file_capture.py
Minor change: it is better to handle a FileNotFoundError than an Exception.
> a more specific exception

- src/pyshark/capture/capture.py
- src/pyshark/capture/file_capture.py
- src/pyshark/capture/inmem_capture.py
- src/pyshark/capture/live_capture.py
- src/pyshark/capture/live_ring_capture.py
- src/pyshark/capture/pipe_capture.py
This is paired up with #257 as I am attempting to pass the raw data up through pyshark so i can access it within my python application.
> Added option for raw as shown in #188

- src/pyshark/capture/capture.py
Hello there ! I need to add custom parameters to Tshark but unfortunately I want the same parameter (-d) to be used multiple times, which is not possible using a dict...
> Support custom_parameters as a list

- src/pyshark/capture/capture.py
Just a small change to throw a more specific exception type
> Throw TypeError instead of Exception when bad type is provided

- src/pyshark/capture/pipe_capture.py
os.pipe object must be closed using os.close
> Fixing os.pipe closing issue

- src/pyshark/capture/inmem_capture.py
InMemCapture uses the current time when providing a packet to tshark. It would be useful if the time a packet was sniffed could be provided instead. This PR allows a user to pass an optional list of receive times when parsing packets, which is then provided to tshark. Supported in this PR are instances of datetime.datetime and float timestamps.
> Allow the time a packet was sniffed to be passed to tshark in InMemCapture

- src/pyshark/capture/capture.py
> Fix Timeout Error not captured problem

- src/pyshark/capture/capture.py
The fix is pretty easy, if we didn't get to the end of the file and the process is killed it's retval is 1.  we're making an exception for this case.
The issue this is solving is issue #437
> fixes #437 the tshark process crashing on large files

- src/pyshark/tshark/tshark_xml.py
> Fix crash on invalid XML output

- README.md
Added Description for display filters with example code
> Read Me Added Description for display filters with example code

- src/pyshark/capture/file_capture.py
> Check file permissions in FileCapture

- src/pyshark/capture/capture.py
- src/pyshark/capture/file_capture.py
- src/pyshark/capture/live_capture.py
Rather than verifying them in the constructor
> Verify capture settings before starting capture

- requirements.txt
- src/pyshark/cache.py
- src/pyshark/capture/capture.py
- src/pyshark/ek_field_mapping.py
- src/pyshark/packet/layers/ek_layer.py
- src/pyshark/tshark/tshark.py
- src/setup.py
- src/tox.ini
- tests/data/ek_field_mapping.json
- tests/test_ek_field_mapping.py
- tests/tshark/test_tshark_ek.py
Adds field mapping so that fields in the EK parsing will receive their correct type automatically
> Added field mapping for EK 

- src/pyshark/capture/capture.py
> Fix Windows eventloop-related issues

- src/pyshark/capture/pipe_capture.py
Add the capability of to use ek parsing to the PipeCapture class
> add use_ek flag to PipeCapture

- .github/workflows/test.yml
Github CI is free for open source projects
> Continuous Integration

- src/pyshark/capture/capture.py
- src/setup.py
- tests/test_cap_operations.py
---
name: Feature request
about: Add async callback support for apply_on_packets
title: ''Add async callback support for apply_on_packets"
labels: enhancement
assignees: ''rudiemeant@gmail.com"
---
**Is your feature request related to a problem? Please describe.**
I've been working on a project where we needed to combine our main event loop and pyshark. It wasn't possible to use coroutines, so I needed to patch the LiveCapture class in order for it to be fully async.
**Describe the solution you'd like**
I added a check using `inspect.iscoroutinefunction` 
**Describe alternatives you've considered**
None
**Additional context**
A test case was added
> Add async callback support for apply_on_packets

- src/pyshark/tshark/output_parser/tshark_xml.py
As my comment in the issue #648 , modify the condition is helpful to the bug when setting `only_summaries` to `True`. The same bug was rise in the issue #250 ,issue #604 , etc.
> Fix issue #648 which setting only_summaries to True lead to a bug
